/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_browser_CefRequestContext_N */

#ifndef _Included_org_cef_browser_CefRequestContext_N
#define _Included_org_cef_browser_CefRequestContext_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_GetGlobalContext
 * Signature: ()Lorg/cef/browser/CefRequestContext_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1GetGlobalContext
  (JNIEnv *, jclass);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_CreateContext
 * Signature: (Lorg/cef/handler/CefRequestContextHandler;)Lorg/cef/browser/CefRequestContext_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1CreateContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_IsGlobal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1IsGlobal
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_CefRequestContext_DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1CefRequestContext_1DTOR
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_ClearCertificateExceptions
 * Signature: (JLorg/cef/callback/CefCompletionCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1ClearCertificateExceptions
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_CloseAllConnections
 * Signature: (JLorg/cef/callback/CefCompletionCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1CloseAllConnections
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_SetChromeColorScheme
 * Signature: (Lorg/cef/browser/CefColorVariant;J)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1SetChromeColorScheme
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_GetChromeColorSchemeMode
 * Signature: ()Lorg/cef/browser/CefColorVariant;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1GetChromeColorSchemeMode
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefRequestContext_N
 * Method:    N_GetChromeColorSchemeColor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_cef_browser_CefRequestContext_1N_N_1GetChromeColorSchemeColor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
